# Generated by Django 3.0.7 on 2020-06-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200604_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='h_name',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
