# Generated by Django 3.0.7 on 2020-06-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_form_h_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='h_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='app.Hospital'),
        ),
    ]
