# Generated by Django 3.0.7 on 2020-06-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200604_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='h_name',
            new_name='hname',
        ),
    ]
